# Docker Compose for Local Testing
version: '3.8'

services:
  wine-quality-app:
    build: .
    container_name: wine-quality-predictor
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - PORT=8000
    volumes:
      - ./artifacts:/app/artifacts
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: wine-quality-network
